### ISSUE TITLE
[FEATURE REQUEST] Add all new users (including ldap) to a specific group

### ISSUE THREAD

**Issue by tanertas** [Smile-SA/redmine_smile_auto_user_activation#1]
It would be nice to this plugin evolve into general purpose rules for new users eg: adding them to  a specific group.

**Comment by Utopism** [comment]
Hi,
It could be a nice feature. I'm working on it.

**Comment by Utopism** [comment]
Done, see V1.0.2

**Comment by tanertas** [comment]
Thank you for fast response. I tested it with both for LDAP and Internal user. I defined a group name by typing the name of an existing group as "New Users" (without double quotes) in text box on Configuration menu. But it didn't work.

**Comment by Utopism** [comment]
Hi, I am going to provide a new version that enables traces. Does the user was already member of the group ? If this is the case, nothing is done.

**Comment by Utopism** [comment]
Check **V1.0.3** that includes an option to add traces in **log/production.log**

look at lines that include **auto_user_activation**

**Comment by tanertas** [comment]
I'm seeing the log below but nothing happens actually. New users don't added to the group "New Users".

`2019-04-28 14:50:20.967 +0300] (7425)  INFO    Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxxxx", "settings"=>{"assign_newly_activated_user_to_group"=>"New Users", "debug"=>"1"}, "commit"=>"Uygula", "id"=>"redmine_smile_auto_user_activation"}`

**Comment by Utopism** [comment]
Hi, the only explanation I see is that the create action is not overridden correctly (overridden by another plug-in ?).
This plug-in does not trigger an error in this case. I am providing a new version that enforces that.

**Comment by Utopism** [comment]
You can try V1.0.4.

In the plugin settings do you have something like that :

[8] override(s) added by the plugin (2019-05-03 21:07:18) :
1 plugin  redmine_smile_auto_user_activation V1.0.3
2 MembersController instance_methods  create < SM::CO::MembersOverride::AutoUserActivation)
3&nbsp;ApplicationHelper&nbsp;instance_methods&nbsp;principals_check_box_tags&nbsp;<&nbsp;SM::HO::AppOverride::AutoUserActivation)
4&nbsp;MembersHelper&nbsp;instance_methods&nbsp;&nbsp;render_principals_for_new_members&nbsp;<&nbsp;SM::HO::MembersOverride::AutoUserActivation)
5&nbsp;GroupsHelper&nbsp;instance_methods&nbsp;&nbsp;render_principals_for_new_group_users&nbsp;<&nbsp;SM::HO::GroupsOverride::AutoUserActivation)
6 UsersHelper instance_methods  change_status_link < SM::HO::UsersOverride::AutoUserActivation)
8&nbsp;Principal&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;scope&nbsp;&nbsp;active_or_to_activate;visible_any_status&nbsp;<&nbsp;SM::MO::PrincipalOverride::AutoUserActivation)

**Comment by Utopism** [comment]
What gives the output of the following command, (typed from the root of the application) ?
> tail -n 5000 -f log/production.log | grep --color=auto 'o=>'

**Comment by tanertas** [comment]
> What gives the output of the following command, (typed from the root of the application) ?
> 
> > tail -n 5000 -f log/production.log | grep --color=auto 'o=>'

Unfortunately V1.0.4 didn't work either. Log doesn"t put anything contains 'o=>' so there's no output with this command.

I have config lines below (debug is checked):

```
1                                     plugin  redmine_smile_auto_user_activation V1.0.4
2     MembersController     instance_methods  create < (SM::CO::MembersOverride::AutoUserActivation)
3     ApplicationHelper     instance_methods  principals_check_box_tags < (SM::HO::AppOverride::AutoUserActivation)
4     MembersHelper         instance_methods  render_principals_for_new_members < (SM::HO::MembersOverride::AutoUserActivation)
5     GroupsHelper          instance_methods  render_principals_for_new_group_users < (SM::HO::GroupsOverride::AutoUserActivation)
6     UsersHelper           instance_methods  change_status_link < (SM::HO::UsersOverride::AutoUserActivation)
8     Principal                        scope  active_or_to_activate;visible_any_status < (SM::MO::PrincipalOverride::AutoUserActivation) 
```

**Comment by Utopism** [comment]
Ok it seems your logger is configured in a way that does not displays info messages.
Don't know how it is possible.

**Comment by Utopism** [comment]
perhaps logs go to another file ?

**Comment by tanertas** [comment]
I mean, I got logs with 'o=>' but there is no any log lines with 'o=>'   **during new account creation.**
```
o=>
o=>Starting Smile Auto User Activation plugin for Redmine
o=>Application user : redmine
o=>
o=>Starting Smile Auto User Activation plugin for Redmine
o=>Application user : redmine
o=>
o=>Starting Smile Auto User Activation plugin for Redmine
o=>Application user : redmine
[2019-05-04 00:46:08.419 +0300] (4792)  INFO init.rb:77:in `block in <top (required)>' o=>
[2019-05-04 00:46:08.419 +0300] (4792)  INFO init.rb:78:in `block in <top (required)>' o=>\__ redmine_smile_auto_user_activation V1.0.4
[2019-05-04 00:46:08.419 +0300] (4792)  INFO smile_tools.rb:122:in `trace_override' o=>1                                     plugin  redmine_smile_auto_user_activation V1.0.4
[2019-05-04 00:46:08.424 +0300] (4792)  INFO init.rb:152:in `block in <top (required)>' o=>----- CONTROLLERS
[2019-05-04 00:46:08.456 +0300] (4792)  INFO smile_tools.rb:122:in `trace_override' o=>2     MembersController     instance_methods  create < (SM::CO::MembersOverride::AutoUserActivation)
[2019-05-04 00:46:08.457 +0300] (4792)  INFO init.rb:161:in `block in <top (required)>' o=>----- HELPERS
[2019-05-04 00:46:08.457 +0300] (4792)  INFO smile_tools.rb:122:in `trace_override' o=>3     ApplicationHelper     instance_methods  principals_check_box_tags < (SM::HO::AppOverride::AutoUserActivation)
[2019-05-04 00:46:08.458 +0300] (4792)  INFO smile_tools.rb:122:in `trace_override' o=>4     MembersHelper         instance_methods  render_principals_for_new_members < (SM::HO::MembersOverride::AutoUserActivation)
[2019-05-04 00:46:08.459 +0300] (4792)  INFO smile_tools.rb:122:in `trace_override' o=>5     GroupsHelper          instance_methods  render_principals_for_new_group_users < (SM::HO::GroupsOverride::AutoUserActivation)
[2019-05-04 00:46:08.481 +0300] (4792)  INFO smile_tools.rb:122:in `trace_override' o=>6     UsersHelper           instance_methods  change_status_link < (SM::HO::UsersOverride::AutoUserActivation)
[2019-05-04 00:46:08.482 +0300] (4792)  INFO init.rb:185:in `block in <top (required)>' o=>----- MODELS
[2019-05-04 00:46:08.482 +0300] (4792)  INFO smile_tools.rb:122:in `trace_override' o=>8     Principal                        scope  active_or_to_activate;visible_any_status < (SM::MO::PrincipalOverride::AutoUserActivation)
[2019-05-04 00:46:08.482 +0300] (4792)  INFO init.rb:196:in `block in <top (required)>' o=>/--
[2019-05-04 00:46:09.416 +0300] (4795)  INFO init.rb:77:in `block in <top (required)>' o=>
[2019-05-04 00:46:09.416 +0300] (4795)  INFO init.rb:78:in `block in <top (required)>' o=>\__ redmine_smile_auto_user_activation V1.0.4
[2019-05-04 00:46:09.416 +0300] (4795)  INFO smile_tools.rb:122:in `trace_override' o=>1                                     plugin  redmine_smile_auto_user_activation V1.0.4
[2019-05-04 00:46:09.421 +0300] (4795)  INFO init.rb:152:in `block in <top (required)>' o=>----- CONTROLLERS
[2019-05-04 00:46:09.470 +0300] (4795)  INFO smile_tools.rb:122:in `trace_override' o=>2     MembersController     instance_methods  create < (SM::CO::MembersOverride::AutoUserActivation)
[2019-05-04 00:46:09.470 +0300] (4795)  INFO init.rb:161:in `block in <top (required)>' o=>----- HELPERS
[2019-05-04 00:46:09.471 +0300] (4795)  INFO smile_tools.rb:122:in `trace_override' o=>3     ApplicationHelper     instance_methods  principals_check_box_tags < (SM::HO::AppOverride::AutoUserActivation)
[2019-05-04 00:46:09.471 +0300] (4795)  INFO smile_tools.rb:122:in `trace_override' o=>4     MembersHelper         instance_methods  render_principals_for_new_members < (SM::HO::MembersOverride::AutoUserActivation)
[2019-05-04 00:46:09.473 +0300] (4795)  INFO smile_tools.rb:122:in `trace_override' o=>5     GroupsHelper          instance_methods  render_principals_for_new_group_users < (SM::HO::GroupsOverride::AutoUserActivation)
[2019-05-04 00:46:09.475 +0300] (4795)  INFO smile_tools.rb:122:in `trace_override' o=>6     UsersHelper           instance_methods  change_status_link < (SM::HO::UsersOverride::AutoUserActivation)
[2019-05-04 00:46:09.475 +0300] (4795)  INFO init.rb:185:in `block in <top (required)>' o=>----- MODELS
[2019-05-04 00:46:09.475 +0300] (4795)  INFO smile_tools.rb:122:in `trace_override' o=>8     Principal                        scope  active_or_to_activate;visible_any_status < (SM::MO::PrincipalOverride::AutoUserActivation)
[2019-05-04 00:46:09.476 +0300] (4795)  INFO init.rb:196:in `block in <top (required)>' o=>/--
[2019-05-04 00:46:09.709 +0300] (4801)  INFO init.rb:77:in `block in <top (required)>' o=>
[2019-05-04 00:46:09.709 +0300] (4801)  INFO init.rb:78:in `block in <top (required)>' o=>\__ redmine_smile_auto_user_activation V1.0.4
[2019-05-04 00:46:09.710 +0300] (4801)  INFO smile_tools.rb:122:in `trace_override' o=>1                                     plugin  redmine_smile_auto_user_activation V1.0.4
[2019-05-04 00:46:09.715 +0300] (4801)  INFO init.rb:152:in `block in <top (required)>' o=>----- CONTROLLERS
[2019-05-04 00:46:09.743 +0300] (4801)  INFO smile_tools.rb:122:in `trace_override' o=>2     MembersController     instance_methods  create < (SM::CO::MembersOverride::AutoUserActivation)
[2019-05-04 00:46:09.744 +0300] (4801)  INFO init.rb:161:in `block in <top (required)>' o=>----- HELPERS
[2019-05-04 00:46:09.744 +0300] (4801)  INFO smile_tools.rb:122:in `trace_override' o=>3     ApplicationHelper     instance_methods  principals_check_box_tags < (SM::HO::AppOverride::AutoUserActivation)
[2019-05-04 00:46:09.745 +0300] (4801)  INFO smile_tools.rb:122:in `trace_override' o=>4     MembersHelper         instance_methods  render_principals_for_new_members < (SM::HO::MembersOverride::AutoUserActivation)
[2019-05-04 00:46:09.746 +0300] (4801)  INFO smile_tools.rb:122:in `trace_override' o=>5     GroupsHelper          instance_methods  render_principals_for_new_group_users < (SM::HO::GroupsOverride::AutoUserActivation)
[2019-05-04 00:46:09.748 +0300] (4801)  INFO smile_tools.rb:122:in `trace_override' o=>6     UsersHelper           instance_methods  change_status_link < (SM::HO::UsersOverride::AutoUserActivation)
[2019-05-04 00:46:09.748 +0300] (4801)  INFO init.rb:185:in `block in <top (required)>' o=>----- MODELS
[2019-05-04 00:46:09.749 +0300] (4801)  INFO smile_tools.rb:122:in `trace_override' o=>8     Principal                        scope  active_or_to_activate;visible_any_status < (SM::MO::PrincipalOverride::AutoUserActivation)
```

**Comment by Utopism** [comment]
Oh great 'o=>' is just a tag I use to identify plugin loading, it does not appear after application initialization.
Can you provide all the logs that happen during creation ? between :
**Started GET ....**
and
**Completed 200 OK ...**

**Comment by tanertas** [comment]
Hope it helps:

```INFO  Started GET "/login?back_url=https%3A%2F%2Fredminetest.*******%2F" for 127.0.0.1 at 2019-05-06 18:10:35 +0300
INFO  Processing by AccountController#login as HTML
INFO    Parameters: {"back_url"=>"https://redminetest.*******/"}
INFO application_controller.rb:93:in `user_setup'   Current user: anonymous
INFO sudo_mode.rb:63:in `sudo_mode'   Rendered account/login.html.erb within layouts/base (42.1ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/redmine_contacts/app/views/contacts_issues/_additional_assets.html.erb (2.0ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/redmine_wysiwyg_editor/app/views/redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial.html.erb (2.0ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (2.3ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.7ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/redmine_contacts/app/views/common/_contacts_select2_data.html.erb (4.5ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (10.9ms)
INFO  Completed 200 OK in 507ms (Views: 390.6ms | ActiveRecord: 19.6ms)
INFO  Started POST "/login" for 127.0.0.1 at 2019-05-06 18:10:54 +0300
INFO  Processing by AccountController#login as HTML
INFO    Parameters: {"utf8"=>"✓", "authenticity_token"=>"895076kkWjHUxPLwA6vSNPQY7vpJY/DkWfomiL+5bdZZeHdjQK32H2OdgtWxPWchTVNt+YFM265qM+Tcx+MRog==", "back_url"=>"https://redminetest.*******/", "username"=>"ttas", "password"=>"[FILTERED]", "login"=>"Giriş"}
INFO application_controller.rb:93:in `user_setup'   Current user: anonymous
INFO user.rb:241:in `try_to_login' User 'ttas' created from external auth source: AuthSourceLdap - *******-dc
INFO account_controller.rb:271:in `successful_authentication' Successful authentication for 'ttas' from 127.0.0.1 at 2019-05-06 15:10:54 UTC
INFO application_controller.rb:399:in `redirect_back_or_default' Redirected to https://redminetest.*******/
INFO  Completed 302 Found in 318ms (ActiveRecord: 60.3ms
INFO  Started GET "/" for 127.0.0.1 at 2019-05-06 18:10:54 +0300
INFO  Processing by WelcomeController#index as HTML
INFO application_controller.rb:93:in `user_setup'   Current user: ttas (id=435)
INFO sudo_mode.rb:63:in `sudo_mode'   Rendered welcome/index.html.erb within layouts/base (89.2ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/redmine_contacts/app/views/contacts_issues/_additional_assets.html.erb (1.6ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/redmine_wysiwyg_editor/app/views/redmine_wysiwyg_editor/_redmine_wysiwyg_editor_partial.html.erb (1.7ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (1.8ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.8ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/redmine_contacts/app/views/common/_contacts_select2_data.html.erb (9.5ms)
INFO view_listener.rb:59:in `block (2 levels) in render_on'   Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (23.5ms)
INFO  Completed 200 OK in 535ms (Views: 448.2ms | ActiveRecord: 48.9ms)```

**Comment by Utopism** [comment]
Hi,

The extract you gave me, do not include the logs happening when a user is added to a project, this is where the interesting debug traces should appear.
It should start with :
> Started POST "/projects/<PROJECT_ID>/memberships" 

Where <PROJECT_ID> is the Identifier of your project

**Comment by tanertas** [comment]
this is an entirely new user. How a newly assigned user supposed to related a project?

**Comment by Utopism** [comment]
Hi, It seems you don't understand how this plugin works :-)
It's aim is to avoid the admins the task to activate new users.
So what does this plugin does is that when a new user is added to it's first project by someone, the user is automatically enabled.
And the enhancement I made for you is that at the same time, the user can be added to a group.

**Comment by tanertas** [comment]
The group that I'm trying to auto assign to new users is the member of the default project. Instead manually adding members to default project, I'm trying to add new users to that group thus making them members of the default project.

**Comment by Utopism** [comment]
So if I understand, what you are talking about is another feature : automatically adding new users to a default project. This is not really in the scope of this plugin.

**Comment by Utopism** [comment]
At some point you need a validation, because if not, any user that creates an account by himself will access to your default project.

**Comment by tanertas** [comment]
> 
> 
> any user that creates an account by himself will access to your default project.

That's exactly what I'm trying to do. This is not a public installation. Every new user is already have an account on LDAP (AD) server.

**Comment by Utopism** [comment]
Hi, so you have the solution to use redmine LDAP integration to add a Group to all users from LDAP.

You can use https://github.com/thorin/redmine_ldap_sync, we use it in our company to do that.

**Comment by tanertas** [comment]
redmine_auto_assign_group plugin is also doing it very well.
https://github.com/two-pack/redmine_auto_assign_group

**Comment by Utopism** [comment]
Indeed !
